# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Creates or updates a comment for a given incident."


class Input:
    APIVERSION = "api-version"
    ETAG = "etag"
    INCIDENTCOMMENTID = "incidentCommentId"
    INCIDENTID = "incidentId"
    PROPERTIESMESSAGE = "propertiesMessage"
    RESOURCEGROUPNAME = "resourceGroupName"
    SUBSCRIPTIONID = "subscriptionId"
    WORKSPACENAME = "workspaceName"
    

class Output:
    AUTHOR = "author"
    CREATEDTIMEUTC = "createdTimeUtc"
    ETAG = "etag"
    ID = "id"
    LASTMODIFIEDTIMEUTC = "lastModifiedTimeUtc"
    MESSAGE = "message"
    NAME = "name"
    TYPE = "type"
    

class CreateCommentInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api-version": {
      "type": "string",
      "title": "API version",
      "description": "The API version to use for this operation.",
      "order": 8
    },
    "etag": {
      "type": "string",
      "title": "etag",
      "description": "etag of the azure resource",
      "order": 7
    },
    "incidentCommentId": {
      "type": "string",
      "title": "Incident Comment ID",
      "description": "Incident Comment ID",
      "order": 1
    },
    "incidentId": {
      "type": "string",
      "title": "Incident ID",
      "description": "Incident ID",
      "order": 2
    },
    "propertiesMessage": {
      "type": "string",
      "title": "Properties Message",
      "description": "The comment message",
      "order": 6
    },
    "resourceGroupName": {
      "type": "string",
      "title": "Resource Group Name",
      "description": "The name of the resource group within the user's subscription. The name is case insensitive.",
      "order": 3
    },
    "subscriptionId": {
      "type": "string",
      "title": "Subscription ID",
      "description": "Azure subscription ID Regex pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$",
      "order": 4
    },
    "workspaceName": {
      "type": "string",
      "title": "Workspace Name",
      "description": "The name of the workspace",
      "order": 5
    }
  },
  "required": [
    "api-version",
    "incidentCommentId",
    "incidentId",
    "propertiesMessage",
    "resourceGroupName",
    "subscriptionId",
    "workspaceName"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateCommentOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "author": {
      "$ref": "#/definitions/person",
      "title": "Author's details",
      "order": 8
    },
    "createdTimeUtc": {
      "type": "string",
      "title": "Message Creation Time",
      "displayType": "date",
      "format": "date-time",
      "order": 6
    },
    "etag": {
      "type": "string",
      "title": "etag",
      "order": 4
    },
    "id": {
      "type": "string",
      "title": "Full Comment ID",
      "order": 1
    },
    "lastModifiedTimeUtc": {
      "type": "string",
      "title": "Message Last Modification Time",
      "displayType": "date",
      "format": "date-time",
      "order": 7
    },
    "message": {
      "type": "string",
      "title": "Incident Message",
      "order": 5
    },
    "name": {
      "type": "string",
      "title": "Comment ID",
      "order": 2
    },
    "type": {
      "type": "string",
      "title": "Name",
      "order": 3
    }
  },
  "definitions": {
    "person": {
      "type": "object",
      "title": "person",
      "properties": {
        "authorsName": {
          "type": "string",
          "title": "Person's name",
          "order": 4
        },
        "email": {
          "type": "string",
          "title": "Persons's Email",
          "order": 2
        },
        "objectId": {
          "type": "string",
          "title": "Person's Object ID",
          "order": 1
        },
        "userPrincipalName": {
          "type": "string",
          "title": "Persons's principal name",
          "order": 3
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
