# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Append tags to a threat intelligence indicator."


class Input:
    NAME = "name"
    THREATINTELLIGENCETAGS = "threatIntelligenceTags"
    

class Output:
    pass

class AppendTagsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "name": {
      "type": "string",
      "title": "Threat intelligence indicator name field.",
      "description": "Threat intelligence indicator name field.",
      "order": 1
    },
    "threatIntelligenceTags": {
      "type": "array",
      "title": "List of tags to be appended.",
      "description": "List of tags to be appended.",
      "items": {
        "type": "string"
      },
      "order": 2
    }
  },
  "required": [
    "name"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AppendTagsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
