# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name="carbon_black_defense-rapid7_a_blakley-plugin",
      version="3.0.0",
      description="Find events and retrieve details for specific events",
      author="rapid7_a_blakley",
      author_email="",
      url="",
      packages=find_packages(),
      install_requires=['insightconnect-plugin-runtime'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_carbon_black_defense']
      )
