# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Query threat intelligence indicators as per filtering criteria."


class Input:
    APIVERSION = "api-version"
    IDS = "ids"
    INCLUDEDISABLED = "includeDisabled"
    KEYWORDS = "keywords"
    MAXCONFIDENCE = "maxConfidence"
    MAXVALIDUNTIL = "maxValidUntil"
    MINCONFIDENCE = "minConfidence"
    MINVALIDUNTIL = "minValidUntil"
    PAGESIZE = "pageSize"
    PATTERNTYPES = "patternTypes"
    RESOURCEGROUPNAME = "resourceGroupName"
    SKIPTOKEN = "skipToken"
    SORTBY = "sortBy"
    SOURCES = "sources"
    SUBSCRIPTIONID = "subscriptionId"
    THREATTYPES = "threatTypes"
    WORKSPACENAME = "workspaceName"
    

class Output:
    INDICATORS = "indicators"
    

class QueryIndicatorsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api-version": {
      "type": "string",
      "title": "API version",
      "description": "The API version to use for this operation.",
      "order": 4
    },
    "ids": {
      "type": "array",
      "title": "Threat Inteligence Indicators Ids",
      "description": "Ids of threat intelligence indicators",
      "items": {
        "type": "string"
      },
      "order": 5
    },
    "includeDisabled": {
      "type": "boolean",
      "title": "Include Disabled Indicators",
      "description": "Parameter to include/exclude disabled indicators.",
      "order": 6
    },
    "keywords": {
      "type": "array",
      "title": "Keywords",
      "description": "Keywords for searching threat intelligence indicators",
      "items": {
        "type": "string"
      },
      "order": 7
    },
    "maxConfidence": {
      "type": "integer",
      "title": "Maximum Confidence",
      "description": "Maximum confidence.",
      "order": 8
    },
    "maxValidUntil": {
      "type": "string",
      "title": "End time for ValidUntil filter.",
      "description": "End time for ValidUntil filter.",
      "order": 10
    },
    "minConfidence": {
      "type": "integer",
      "title": "Minimum Confidence",
      "description": "Minimum confidence.",
      "order": 9
    },
    "minValidUntil": {
      "type": "string",
      "title": "Start time for ValidUntil filter.",
      "description": "Start time for ValidUntil filter.",
      "order": 11
    },
    "pageSize": {
      "type": "integer",
      "title": "Page Size.",
      "description": "Page Size.",
      "order": 12
    },
    "patternTypes": {
      "type": "integer",
      "title": "Pattern Types.",
      "description": "Pattern Types.",
      "order": 13
    },
    "resourceGroupName": {
      "type": "string",
      "title": "Resource Group Name",
      "description": "The name of the resource group within the user's subscription. The name is case insensitive.",
      "order": 1
    },
    "skipToken": {
      "type": "string",
      "title": "Skip Token.",
      "description": "Skip Token.",
      "order": 14
    },
    "sortBy": {
      "type": "array",
      "title": "Sort By",
      "description": "Columns to sort by and sorting order",
      "items": {
        "$ref": "#/definitions/ThreatIntelligenceSortingCriteria"
      },
      "order": 15
    },
    "sources": {
      "type": "array",
      "title": "Sources of threat intelligence indicators.",
      "description": "Sources of threat intelligence indicators.",
      "items": {
        "type": "string"
      },
      "order": 16
    },
    "subscriptionId": {
      "type": "string",
      "title": "Subscription ID",
      "description": "Azure subscription ID Regex pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$",
      "order": 2
    },
    "threatTypes": {
      "type": "array",
      "title": "Threat Types of Threat Inteligence Indicators.",
      "description": "Threat Types of Threat Inteligence Indicators.",
      "items": {
        "type": "string"
      },
      "order": 17
    },
    "workspaceName": {
      "type": "string",
      "title": "Workspace Name",
      "description": "The name of the workspace",
      "order": 3
    }
  },
  "required": [
    "api-version",
    "resourceGroupName",
    "subscriptionId",
    "workspaceName"
  ],
  "definitions": {
    "ThreatIntelligenceSortingCriteria": {
      "type": "object",
      "title": "ThreatIntelligenceSortingCriteria",
      "properties": {
        "itemKey": {
          "type": "string",
          "title": "Item Key.",
          "description": "Column name to sort by.",
          "order": 1
        },
        "sortOrder": {
          "type": "string",
          "title": "Sorting Order.",
          "description": "Sorting Order.",
          "enum": [
            "ascending",
            "descending",
            "unsorted"
          ],
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class QueryIndicatorsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "indicators": {
      "type": "array",
      "title": "Threat Intelligence Indicators.",
      "description": "output threat intelligence indicators.",
      "items": {
        "type": "object"
      },
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
