# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Update existing threat intelligence indicator"


class Input:
    ETAG = "etag"
    NAME = "name"
    PROPERTIES = "properties"
    

class Output:
    pass

class UpdateIndicatorInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "etag": {
      "type": "string",
      "title": "Etag of the azure resource",
      "description": "Etag of the azure resource",
      "order": 2
    },
    "name": {
      "type": "string",
      "title": "Threat intelligence indicator name field.",
      "description": "Threat intelligence indicator name field.",
      "order": 1
    },
    "properties": {
      "$ref": "#/definitions/ThreatIntelligenceIndicatorProperties",
      "title": "Properties of the intelligence indicator.",
      "description": "Object containing all the necessary properties to conclude a query.",
      "order": 3
    }
  },
  "required": [
    "name",
    "properties"
  ],
  "definitions": {
    "ThreatIntelligenceExternalReference": {
      "type": "object",
      "title": "ThreatIntelligenceExternalReference",
      "properties": {
        "description": {
          "type": "string",
          "title": "External reference description",
          "description": "External reference description",
          "order": 1
        },
        "externalId": {
          "type": "string",
          "title": "External reference ID",
          "description": "External reference ID",
          "order": 2
        },
        "hashes": {
          "type": "object",
          "title": "External reference hashes",
          "description": "External reference hashes",
          "order": 3
        },
        "sourceName": {
          "type": "string",
          "title": "External reference source name",
          "description": "External reference source name",
          "order": 4
        },
        "url": {
          "type": "string",
          "title": "External reference URL",
          "description": "External reference URL",
          "order": 5
        }
      }
    },
    "ThreatIntelligenceGranularMarkingModel": {
      "type": "object",
      "title": "ThreatIntelligenceGranularMarkingModel",
      "properties": {
        "language": {
          "type": "string",
          "title": "Language granular marking model",
          "description": "Language granular marking model",
          "order": 1
        },
        "markingRef": {
          "type": "integer",
          "title": "marking reference granular marking model",
          "description": "marking reference granular marking model",
          "order": 2
        },
        "selectors": {
          "type": "array",
          "title": "granular marking model selectors",
          "description": "granular marking model selectors",
          "items": {
            "type": "string"
          },
          "order": 3
        }
      }
    },
    "ThreatIntelligenceIndicatorProperties": {
      "type": "object",
      "title": "ThreatIntelligenceIndicatorProperties",
      "properties": {
        "confidence": {
          "type": "integer",
          "title": "Confidence of threat intelligence entity",
          "description": "Confidence of threat intelligence entity",
          "order": 1
        },
        "created": {
          "type": "string",
          "title": "Created by",
          "description": "Created by",
          "order": 2
        },
        "createdByRef": {
          "type": "string",
          "title": "Created by reference of threat intelligence entity",
          "description": "Created by reference of threat intelligence entity",
          "order": 3
        },
        "defanged": {
          "type": "boolean",
          "title": "Is threat intelligence entity defanged",
          "description": "Is threat intelligence entity defanged",
          "order": 4
        },
        "description": {
          "type": "string",
          "title": "Description of a threat intelligence entity",
          "description": "Description of a threat intelligence entity",
          "order": 5
        },
        "displayName": {
          "type": "string",
          "title": "Display name of a threat intelligence entity",
          "description": "Display name of a threat intelligence entity",
          "order": 6
        },
        "externalId": {
          "type": "string",
          "title": "External ID of threat intelligence entity",
          "description": "External ID of threat intelligence entity",
          "order": 7
        },
        "externalLastUpdatedTimeUtc": {
          "type": "string",
          "title": "External last updated time in UTC",
          "description": "External last updated time in UTC",
          "order": 8
        },
        "externalReferences": {
          "type": "array",
          "title": "External References",
          "description": "External References",
          "items": {
            "$ref": "#/definitions/ThreatIntelligenceExternalReference"
          },
          "order": 9
        },
        "granularMarkings": {
          "type": "array",
          "title": "Granular Markings",
          "description": "Granular Markings",
          "items": {
            "$ref": "#/definitions/ThreatIntelligenceGranularMarkingModel"
          },
          "order": 10
        },
        "indicatorTypes": {
          "type": "array",
          "title": "Indicator types of threat intelligence entities",
          "description": "Indicator types of threat intelligence entities",
          "items": {
            "type": "string"
          },
          "order": 11
        },
        "killChainPhases": {
          "type": "array",
          "title": "Kill chain phases",
          "description": "Kill chain phases",
          "items": {
            "$ref": "#/definitions/ThreatIntelligenceKillChainPhase"
          },
          "order": 12
        },
        "labels": {
          "type": "array",
          "title": "Labels of threat intelligence entity",
          "description": "Labels of threat intelligence entity",
          "items": {
            "type": "string"
          },
          "order": 13
        },
        "language": {
          "type": "string",
          "title": "Language of threat intelligence entity",
          "description": "Language of threat intelligence entity",
          "order": 14
        },
        "lastUpdatedTimeUtc": {
          "type": "string",
          "title": "Last updated time in UTC",
          "description": "Last updated time in UTC",
          "order": 15
        },
        "modified": {
          "type": "string",
          "title": "Modified by",
          "description": "Modified by",
          "order": 16
        },
        "objectMarkingRefs": {
          "type": "array",
          "title": "Threat intelligence entity object marking references",
          "description": "Threat intelligence entity object marking references",
          "items": {
            "type": "string"
          },
          "order": 17
        },
        "parsedPattern": {
          "type": "array",
          "title": "Parsed patterns",
          "description": "Parsed patterns",
          "items": {
            "$ref": "#/definitions/ThreatIntelligenceParsedPattern"
          },
          "order": 18
        },
        "pattern": {
          "type": "string",
          "title": "Pattern of a threat intelligence entity",
          "description": "Pattern of a threat intelligence entity",
          "order": 19
        },
        "patternType": {
          "type": "string",
          "title": "Pattern type of a threat intelligence entity",
          "description": "Pattern type of a threat intelligence entity",
          "order": 20
        },
        "patternVersion": {
          "type": "string",
          "title": "Pattern version of a threat intelligence entity",
          "description": "Pattern version of a threat intelligence entity",
          "order": 21
        },
        "revoked": {
          "type": "boolean",
          "title": "Is threat intelligence entity revoked",
          "description": "Is threat intelligence entity revoked",
          "order": 22
        },
        "source": {
          "type": "string",
          "title": "Source of a threat intelligence entity",
          "description": "Source of a threat intelligence entity",
          "order": 23
        },
        "threatIntelligenceTags": {
          "type": "array",
          "title": "List of tags",
          "description": "List of tags",
          "items": {
            "type": "string"
          },
          "order": 24
        },
        "threatTypes": {
          "type": "array",
          "title": "Threat types",
          "description": "Threat types",
          "items": {
            "type": "string"
          },
          "order": 25
        },
        "validFrom": {
          "type": "string",
          "title": "Valid from",
          "description": "Valid from",
          "order": 26
        },
        "validUntil": {
          "type": "string",
          "title": "Valid until",
          "description": "Valid until",
          "order": 27
        }
      },
      "definitions": {
        "ThreatIntelligenceExternalReference": {
          "type": "object",
          "title": "ThreatIntelligenceExternalReference",
          "properties": {
            "description": {
              "type": "string",
              "title": "External reference description",
              "description": "External reference description",
              "order": 1
            },
            "externalId": {
              "type": "string",
              "title": "External reference ID",
              "description": "External reference ID",
              "order": 2
            },
            "hashes": {
              "type": "object",
              "title": "External reference hashes",
              "description": "External reference hashes",
              "order": 3
            },
            "sourceName": {
              "type": "string",
              "title": "External reference source name",
              "description": "External reference source name",
              "order": 4
            },
            "url": {
              "type": "string",
              "title": "External reference URL",
              "description": "External reference URL",
              "order": 5
            }
          }
        },
        "ThreatIntelligenceGranularMarkingModel": {
          "type": "object",
          "title": "ThreatIntelligenceGranularMarkingModel",
          "properties": {
            "language": {
              "type": "string",
              "title": "Language granular marking model",
              "description": "Language granular marking model",
              "order": 1
            },
            "markingRef": {
              "type": "integer",
              "title": "marking reference granular marking model",
              "description": "marking reference granular marking model",
              "order": 2
            },
            "selectors": {
              "type": "array",
              "title": "granular marking model selectors",
              "description": "granular marking model selectors",
              "items": {
                "type": "string"
              },
              "order": 3
            }
          }
        },
        "ThreatIntelligenceKillChainPhase": {
          "type": "object",
          "title": "ThreatIntelligenceKillChainPhase",
          "properties": {
            "killChainName": {
              "type": "string",
              "title": "Kill chainName name",
              "description": "Kill chainName name",
              "order": 1
            },
            "phaseName": {
              "type": "string",
              "title": "Phase name",
              "description": "Phase name",
              "order": 2
            }
          }
        },
        "ThreatIntelligenceParsedPattern": {
          "type": "object",
          "title": "ThreatIntelligenceParsedPattern",
          "properties": {
            "patternTypeKey": {
              "type": "string",
              "title": "Pattern Type Key",
              "description": "Pattern Type Key",
              "order": 1
            },
            "patternTypeValues": {
              "type": "array",
              "title": "Pattern Type Values",
              "description": "Pattern Type Values",
              "items": {
                "$ref": "#/definitions/ThreatIntelligenceParsedPatternTypeValue"
              },
              "order": 2
            }
          },
          "definitions": {
            "ThreatIntelligenceParsedPatternTypeValue": {
              "type": "object",
              "title": "ThreatIntelligenceParsedPatternTypeValue",
              "properties": {
                "value": {
                  "type": "string",
                  "title": "Value",
                  "description": "Value",
                  "order": 1
                },
                "valueType": {
                  "type": "string",
                  "title": "Value Type",
                  "description": "Type of the value",
                  "order": 2
                }
              }
            }
          }
        },
        "ThreatIntelligenceParsedPatternTypeValue": {
          "type": "object",
          "title": "ThreatIntelligenceParsedPatternTypeValue",
          "properties": {
            "value": {
              "type": "string",
              "title": "Value",
              "description": "Value",
              "order": 1
            },
            "valueType": {
              "type": "string",
              "title": "Value Type",
              "description": "Type of the value",
              "order": 2
            }
          }
        }
      }
    },
    "ThreatIntelligenceKillChainPhase": {
      "type": "object",
      "title": "ThreatIntelligenceKillChainPhase",
      "properties": {
        "killChainName": {
          "type": "string",
          "title": "Kill chainName name",
          "description": "Kill chainName name",
          "order": 1
        },
        "phaseName": {
          "type": "string",
          "title": "Phase name",
          "description": "Phase name",
          "order": 2
        }
      }
    },
    "ThreatIntelligenceParsedPattern": {
      "type": "object",
      "title": "ThreatIntelligenceParsedPattern",
      "properties": {
        "patternTypeKey": {
          "type": "string",
          "title": "Pattern Type Key",
          "description": "Pattern Type Key",
          "order": 1
        },
        "patternTypeValues": {
          "type": "array",
          "title": "Pattern Type Values",
          "description": "Pattern Type Values",
          "items": {
            "$ref": "#/definitions/ThreatIntelligenceParsedPatternTypeValue"
          },
          "order": 2
        }
      },
      "definitions": {
        "ThreatIntelligenceParsedPatternTypeValue": {
          "type": "object",
          "title": "ThreatIntelligenceParsedPatternTypeValue",
          "properties": {
            "value": {
              "type": "string",
              "title": "Value",
              "description": "Value",
              "order": 1
            },
            "valueType": {
              "type": "string",
              "title": "Value Type",
              "description": "Type of the value",
              "order": 2
            }
          }
        }
      }
    },
    "ThreatIntelligenceParsedPatternTypeValue": {
      "type": "object",
      "title": "ThreatIntelligenceParsedPatternTypeValue",
      "properties": {
        "value": {
          "type": "string",
          "title": "Value",
          "description": "Value",
          "order": 1
        },
        "valueType": {
          "type": "string",
          "title": "Value Type",
          "description": "Type of the value",
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class UpdateIndicatorOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
