# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Gets all the comments for a given incident."


class Input:
    APIVERSION = "api-version"
    FILTER = "filter"
    ORDERBY = "orderBy"
    RESOURCEGROUPNAME = "resourceGroupName"
    SKIPTOKEN = "skipToken"
    SUBSCRIPTIONID = "subscriptionId"
    TOP = "top"
    WORKSPACENAME = "workspaceName"
    

class Output:
    INCIDENTS = "Incidents"
    

class ListIncidentsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api-version": {
      "type": "string",
      "title": "API version",
      "description": "The API version to use for this operation.",
      "order": 4
    },
    "filter": {
      "type": "string",
      "title": "filter the results",
      "description": "Filters the results, based on a Boolean condition. Optional.",
      "order": 5
    },
    "orderBy": {
      "type": "string",
      "title": "order the results",
      "description": "sorts the results",
      "order": 6
    },
    "resourceGroupName": {
      "type": "string",
      "title": "Resource Group Name",
      "description": "The name of the resource group within the user's subscription. The name is case insensitive.",
      "order": 1
    },
    "skipToken": {
      "type": "string",
      "title": "order the results",
      "description": "Skiptoken is only used if a previous operation returned a partial result. If a previous response contains a nextLink element, the value of the nextLink element will include a skiptoken parameter that specifies a starting point to use for subsequent calls.",
      "order": 7
    },
    "subscriptionId": {
      "type": "string",
      "title": "Subscription ID",
      "description": "Azure subscription ID Regex pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$",
      "order": 2
    },
    "top": {
      "type": "integer",
      "title": "Return top results",
      "description": "Return only n first results.",
      "order": 8
    },
    "workspaceName": {
      "type": "string",
      "title": "Workspace Name",
      "description": "The name of the workspace",
      "order": 3
    }
  },
  "required": [
    "api-version",
    "resourceGroupName",
    "subscriptionId",
    "workspaceName"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListIncidentsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "Incidents": {
      "type": "array",
      "title": "List of incidents",
      "description": "list of incidents objects",
      "items": {
        "type": "object"
      },
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
