name: Dump git vars

on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  check-status:

    runs-on: ubuntu-latest

    steps:
      - name: dump variables
        shell: bash
        run:
          env

      - name: check github base ref
        shell: bash
        run:
          echo $GITHUB_BASE_REF